config/routes.rb
Rails.application.routes.draw do
  get 'statistiche/stat'
  root "libri#index"

  get 'registrazione', to: 'utenti#new'
  post 'registrazione', to: 'utenti#create'

  get 'richiedi', to: 'prestiti#create'
  delete 'logout', to: 'sessioni#logout'

  get 'login', to: 'sessioni#new'
  post 'login', to: 'sessioni#create'

  get 'approvare', to: 'libri#approvare'
  get 'approva', to: 'libri#approva'

  resources :libri
  resources :prestiti, only: [:show, :index]

  get 'consegna', to: 'prestiti#consegna'
  get 'restituisci', to: 'prestiti#restituisci'
  post 'restituisci', to: 'prestiti#restituzione'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <!-- NAVBAR start -->
  <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="navbar-menu">
      <%= link_to 'Libri', root_path, class: 'navbar-item' %>
      <%= link_to 'Prestiti', prestiti_path, class: 'navbar-item' %>
      <% if loggato? %>
      <%= link_to 'Logout', logout_path, class: 'navbar-item', method: :delete %>
      <% if utente_corrente.admin? %>
        <%= link_to 'Registra', registrazione_path, class: 'navbar-item' %>
        <%= link_to 'Da approvare', approvare_path, class: 'navbar-item' %>

      <% end %>
      <% end %>
    </div>
    <div class="nabar-brand">
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <script>
    $(document).ready(function() {
        // Check for click events on the navbar burger icon
        $(".navbar-burger").click(function() {

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            $(".navbar-burger").toggleClass("is-active");
            $(".navbar-menu").toggleClass("is-active");

        });
      });
    </script>
  </nav>
  <!-- NAVBAR end -->
  <body>
    <div class="section">
      <% flash.each do |tipo_messaggio, messaggio| %>
          <div class="notification is-<%= tipo_messaggio %>"><%= messaggio %></div>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>